version: '3'
services:
  qiuyu-nginx:
    container_name: qiuyu-nginx
    build:
     context: ./
     dockerfile: ./qiuyu-docker/nginx/nginx-Dockerfile
    ports:
      - "80:80"
    volumes:
     - ./logs/nginx:/var/log/nginx
    depends_on:
      - qiuyu-server
      - nginx-vue

  qiuyu-server:
    container_name: qiuyu-server
    restart: always
    build:
     context: ./
     dockerfile: ./qiuyu-docker/server-Dockerfile
    working_dir: /app
    volumes:
      - ./vtg:/app
    expose:
      - "8091"
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker -Dmaven.test.skip=true
           
  nginx-vue:
    container_name: nginx-vue
    build:
      context: ./
      dockerfile: ./qiuyu-docker/front/Dockerfile
    expose:
     - "9528"
    volumes:
     - ./logs/nginx:/var/log/nginx
    depends_on:
     - qiuyu-server

  qiuyu-redis:
    image: redis
    container_name: qiuyu-redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6378:6378"
    volumes:
      - ./data:/data
      - .qiuyu-docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
