server:
  port: 8099

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  application:
    name: eureka-server
  security:
    user:
      name: user
      password: user
