server:
  port: 8092
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8092/eureka/
spring:
  security:
    user:
      name: user
      password: user
